config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |user| user.role == 'admin' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      delete :cancel_vote
    end
  end

  resources :questions, concerns: [:votable] do
    resources :answers, shallow: true, except: :index, concerns: [:votable] do
      post :best_answer, on: :member
      resources :comments, defaults: { commentable: 'answer' }
    end
    resources :comments, defaults: { commentable: 'question' }
    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  resources :users, only: :show_rewards do
    get :show_rewards, on: :member
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy

  namespace :api do
    namespace :v1 do
      resources :users, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  get '/email', to: 'users#email'
  post '/set_email', to: 'users#set_email'
  get '/search', to: 'search#search'
  
  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable

  belongs_to :author, class_name: 'User'
  belongs_to :best_answer, class_name: 'Answer', optional: true
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :comments, dependent: :destroy, as: :commentable
  has_many :subscriptions, dependent: :destroy
  has_one :reward, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank, allow_destroy: true

  validates :title, :body, presence: true

  ThinkingSphinx::Callbacks.append(
    self, behaviours: [:sql]
  )

  # after_create :subscribe_author

  def set_best_answer(answer)
    transaction do
      update!(best_answer: answer)
      reward&.update!(user: answer.author)
    end
  end

  private

  def subscribe_author
    subscriptions.create!(author: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :set_question, only: %i[show update destroy]

  def index
    @questions = Question.all
    render json: @questions
  end

  def show
    render json: @question
  end

  def create
    @question = current_resource_owner.questions.new(question_params)

    if @question.save
      render json: @question
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def update
    if @question.update(question_params)
      render json: @question
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    if @question.destroy
      render json: @question
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  private

  def set_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, links_attributes: %i[name url id],
                                                    reward_attributes: %i[title image])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[index show]
  before_action :set_question, only: %i[show edit update destroy]
  after_action :publish_question, only: %i[create]

  authorize_resource

  def index
    @questions = Question.all
    gon.current_user_id = current_user&.id
  end

  def show
    @answer = Answer.new
    @best_answer = @question.best_answer
    @other_answers = @question.answers.where.not(id: @question.best_answer_id)
    @answer.links.build
    gon.question_id = @question.id
  end

  def new
    @question = Question.new
    @question.links.build
    @question.build_reward
  end

  def edit; end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Question successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'Question was successfully deleted'
  end

  private

  def set_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/question',
        locals: { question: @question }
      )
    )
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [],
                                                    links_attributes: [:id, :name, :url, :_destroy],
                                                    reward_attributes: [:id, :name, :image, :_destroy])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question do |f|
  p 
    = f.label :title
    = f.text_field :title
  p 
    = f.label :body
    = f.text_area :body
  p 
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
 
  = render 'links/link', resource: @question, f: f
  = render 'rewards/form', resource: @question, f: f

  p = f.submit 'Ask'
  

app/views/questions/_question.html.slim
.question-items
  tr
    td= question.title
    td= link_to 'Show', question_path(question)

app/views/questions/index.html.slim
h1 All Questions

- if can?(:create, Question)
  p= link_to 'Ask question', new_question_path

table
  tr
    th Title
    th colspan=1 Actions
  
  - cache collection_cache_key_for :question do
    = render @questions

app/views/questions/new.html.slim
h1 New Questions

= render 'form'

= link_to 'Back', questions_path

app/views/questions/show.html.slim
- cache @question do
  .questions
    .question-title
      h1= @question.title
    .question-body
      h2= @question.body

    .subscription
      - if current_user && can?(:create, Subscription)
        = render 'subscriptions/subscription', question: @question
    br    
    .question-files
      = render 'shared/attachments', resource: @question
    
    .question-reward
      = render 'rewards/reward', resource: @question
    
    .links
      = render 'links/links_collection', resource: @question

    .rating
      = render 'shared/rating', resource: @question

      - if @best_answer.present?
        h3= @question.best_answer.body

    - if user_signed_in?
      .question-errors
        = render 'shared/errors', resource: @question
      = form_with model: @question, class: 'hidden', html: { id: "edit-question-#{@question.id}" }, local: false do |f|
        p
          - f.label :title
          = f.text_field :title
        p
          - f.label :body
          = f.text_area :body
        p
          - f.label :files
          = f.file_field :files, multiple: true, direct_upload: true
        .question_links
          p = render 'links/link', resource: @question, f: f
        p = f.submit 'Save'
      br
      - if current_user && can?(:update, @question)
        p = link_to 'Edit Question', '#', class: 'edit-question-link', data: { question_id: @question.id }
      - if current_user && can?(:destroy, @question)
        p = link_to 'Delete Question', question_path(@question), method: :delete

  .question
    div class="question-#{@question.id}-comments"
      = render 'comments/comments', resource: @question

    
  h3 All answer

  .answers
    = render @question.answers

  - if user_signed_in?
    h4= 'Your Answer'
    .answer-errors
      = render 'shared/errors', resource: @answer
    = form_with model: [@question, @answer], local: false, class: 'new-answer' do |f|
      - f.label :body
      p = f.text_area :body
      - f.label :files
      p = f.file_field :files, multiple: true, direct_upload: true

      .answer_links
        = render 'links/link', resource: @answer, f: f

      p = f.submit 'Answer'

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% unless @question.errors.present? %>
  $('.questions .question-title').text('<%= @question.title %>');
  $('.questions .question-body').text('<%= @question.body %>');
  $('.questions .links').html('<%= render 'links/links_collection', resource: @question %>');
  $('.questions .question-files').html('<%= render 'shared/attachments', resource: @question %>');
  $('form#edit-question-' + <%= @question.id %>).addClass('hidden');
  $('.edit-question-link').show()
<% end %>