config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |user| user.role == 'admin' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      delete :cancel_vote
    end
  end

  resources :questions, concerns: [:votable] do
    resources :answers, shallow: true, except: :index, concerns: [:votable] do
      post :best_answer, on: :member
      resources :comments, defaults: { commentable: 'answer' }
    end
    resources :comments, defaults: { commentable: 'question' }
    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  resources :users, only: :show_rewards do
    get :show_rewards, on: :member
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy

  namespace :api do
    namespace :v1 do
      resources :users, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  get '/email', to: 'users#email'
  post '/set_email', to: 'users#set_email'
  get '/search', to: 'search#search'
  
  mount ActionCable.server => '/cable'
end

app/views/shared/_attachments.html.slim
- if resource.files.present?
  p Files:
  - if resource.files.attached?
    - resource.files.each do |file|
      p id="attachment_#{file.id}"
        = link_to file.filename.to_s, url_for(file), target: '_blank'
      
      - if current_user && can?(:destroy, file.record)
        = link_to 'Delete file', attachment_path(file), method: :delete, remote: true
        

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message
      

app/views/shared/_flash_message.html.slim
.row.justify-content-center.mt-3
  - flash.each do |key, msg|
    .col.col-md-4
      div class=("text-center #{flash_class(key)}") role="alert" 
        = msg.html_safe

app/views/shared/_nav.html.slim
.border
  nav.navbar.navbar-light.bg-light.shadow
    .container
      = link_to 'QnA', root_path, class: 'navbar-brand'
      = render 'search/form'
      span.navbar-text
        - if user_signed_in?
          b=> current_user.email
          => link_to show_rewards_user_path(current_user) do 
            'Rewards
            i.bi.bi-trophy
          '|
          =< link_to 'Log out', destroy_user_session_path, method: :delete
        - else
          => link_to 'Log in', new_user_session_path
          '|
          =< link_to 'Sign up', new_user_registration_path

app/views/shared/_rating.html.slim
'Rating:
.value 
  = resource.rating_value
- unless !user_signed_in? || (current_user && cannot?(:vote, resource))
  = link_to 'Cancel vote', polymorphic_path(resource, action: :cancel_vote),
          method: :delete,
          remote: true,
          data: { type: :json },
          class: 'cancel-vote-link',
          style: "#{current_user&.voted?(resource) ? '' : 'display:none;'}"
  => link_to 'UP', polymorphic_path(resource, action: :vote_up),
          method: :patch,
          remote: true,
          data: { type: :json },
          class: 'vote-up-link',
          style: "#{current_user&.voted?(resource) ? 'display:none;' : ''}"
  =< link_to 'DOWN', polymorphic_path(resource, action: :vote_down),
          method: :patch,
          remote: true,
          data: { type: :json },
          class: 'vote-down-link',
          style: "#{current_user&.voted?(resource) ? 'display:none;' : ''}"