config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |user| user.role == 'admin' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      delete :cancel_vote
    end
  end

  resources :questions, concerns: [:votable] do
    resources :answers, shallow: true, except: :index, concerns: [:votable] do
      post :best_answer, on: :member
      resources :comments, defaults: { commentable: 'answer' }
    end
    resources :comments, defaults: { commentable: 'question' }
    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  resources :users, only: :show_rewards do
    get :show_rewards, on: :member
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy

  namespace :api do
    namespace :v1 do
      resources :users, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  get '/email', to: 'users#email'
  post '/set_email', to: 'users#set_email'
  get '/search', to: 'search#search'
  
  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable

  belongs_to :question, touch: true
  belongs_to :author, class_name: 'User'
  has_many :links, dependent: :destroy, as: :linkable
  has_many :comments, dependent: :destroy, as: :commentable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  after_create :send_notifications

  ThinkingSphinx::Callbacks.append(
    self, behaviours: [:sql]
  )

  private

  def send_notifications
    NotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[show]
  before_action :set_answer, only: %i[show update destroy best_answer]
  before_action :set_question, only: %i[create]
  after_action :publish_answer, only: :create

  authorize_resource

  def show; end

  def new; end

  def create
    @answer = @question.answers.create(answer_params)
    @answer.author = current_user
    @answer.save
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def destroy
    @answer.destroy
    @question = @answer.question
    flash.now[:notice] = 'Answer was successfully deleted'
  end

  def best_answer
    @question = @answer.question
    @question.set_best_answer(@answer)

    @best_answer = @question.best_answer
    @other_answers = @question.answers.where.not(id: @question.best_answer_id)
  end

  private

  def set_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "questions/#{@answer.question_id}",
      answer: @answer
    )
  end

  def answer_params
    params.require(:answer).permit(:body, files: [],
                                          links_attributes: [:id, :name, :url, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :set_answer, only: %i[show update destroy]
  before_action :set_question, only: %i[index show create]

  def index
    @answers = @question.answers
    render json: @answers
  end

  def show
    render json: @answer
  end

  def create
    @answer = current_resource_owner.answers.new(answer_params.merge(question_id: params[:question_id]))

    if @answer.save
      render json: @answer
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def update
    if @answer.update(answer_params)
      render json: @answer
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    if @answer.destroy
      render json: @answer
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  private

  def set_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def set_question
    @question ||= params[:question_id] ? Question.with_attached_files.find(params[:question_id]) : @answer.question
  end

  def answer_params
    params.require(:answer).permit(:body, :question_id, links_attributes: %i[name url id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  - cache answer do
    table
      tr class='.other-answers'
        td= answer.body
        - if current_user&.author?(@question) && (current_user && can?(:best_answer, answer))
          td= link_to 'Best answer', best_answer_answer_path(answer), method: :post, remote: true
        - if current_user && can?(:update, answer)
          td= link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
        - if current_user && can?(:destroy, answer)
          td= link_to 'Delete answer',
                      answer_path(answer),
                      method: :delete, 
                      remote: true

      tr class="answer-id-#{answer.id}"
        td class='rating'
          = render 'shared/rating', resource: answer

      tr
        td class="answer-#{answer.id}-comments"
          = render 'comments/comments', resource: answer

    .links
      = render 'links/links_collection', resource: answer
    
    p= form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" }, local: false do |f|
      .edit-answer-errors
        div class=["answer-error-#{answer.id}"]
        p 
          - f.label :body
          = f.text_area :body
        p
          - f.label :files
          = f.file_field :files, multiple: true, direct_upload: true
        p = render 'links/link', resource: @question, f: f
        p = f.submit 'Save'

    p= render 'shared/attachments', resource: answer
  hr

app/views/answers/_best_answer.html.slim
- if resource&.persisted?
  - cache resource do
    h4 The best answer
    p= resource.body
    p= render 'shared/attachments', resource: resource
    p= render 'links/links_collection', resource: @question
    p= render 'shared/rating', resource: @answer
hr

app/views/answers/best_answer.js.erb
<% if @best_answer.present? %>
  $('.answers').html('<%= render 'answers/best_answer', resource: @best_answer %>');
  $('.answers').append('<%= j render @other_answers %>');
<% end %>

app/views/answers/create.js.erb
document.querySelector('.answer-errors').innerHTML = '<%= render 'shared/errors', resource: @answer %>';

<% if @answer.persisted? %>
  window.location.reload()
  document.querySelector('.answers').insertAdjacentHTML('beforeend', '<%= j render @answer %>')
  document.querySelector('.new-answer #answer_body').value = ''
  document.querySelector('.new-name').value = ''
  document.querySelector('.new-url').value = ''
  document.querySelector('.nested-fields').remove()
<% end %>

app/views/answers/destroy.js.erb
<% unless @answer.persisted? %>
  $('.flash-message').html('<%= render 'shared/flash_message' %>');
  $('.answers').html('<%= j render @answer.question.answers %>');
<% end %>

app/views/answers/update.js.erb
$('.edit-answer-errors .answer-error-<%= @answer.id %>').html('<%= render 'shared/errors', resource: @answer %>');

<% unless @answer.errors.present? %>
  $('.answers .answer-id-<%= @answer.id %>').remove();
  $('.answers').html('<%= j render @question.answers %>');
<% end %>